#+TITLE Intro til samtidig redigering
* En innovasjonsdag en gang for lenge sen
- Jeg og Snorre Brekke ønsket å lage en innholdseditor som støttet samtidig redigiering
- Bakket av firebase, med konflikt-minimering
* Disclaimer
- Dette er akademiskt
- Jeg har ikke helt skjønt alt
- Jeg har ikke gått full snowball-runde og lest alt
- Fokusert på en spesifik CRDT-algoritme
* Hvordan fungerer en 'ordentlig' samtidig editor?
** Causality, Convergence and Intention preservation
*** Causality
Alle operasjoner må utføres i samme rekkefølge på alle klienter
*** Convergence
Alle klienter ser det samme
*** Intention preservation
Det du gjør påvirkes ikke av andre endringer som kommer fra andra klienter
* Operational Transform
Brukes av feks google docs
** Basics
- Sender kommandoer basert på index fra kilde-klient til andre
- Insert{4, 'x'} eller Delete{3, 'y'}
- Operasjoner må gjøres i samme rekkefølge på alle klienter
eller transformeres (Operational Transform)
** Ulemper
- Vanskelig å få transformasjonen til å fungere med mange klienter
** Kan man gjøre det enklere?
* CRDT – Conflict-free Replicated Data Type
** Datatyper med innebygd eventual consistency
- Counters
- Set
- Sekvense

** Brukes av en del distribuerte databaser
Talk på ndc i år for interesserte
 https://ndcoslo.com/talk/living-in-eventually-consistent-reality/ 

** Sekvensielle CRDT
kan brukes som alternativ til Operational Transform.
* WoOT
Witout Operational Transform
https://hal.inria.fr/inria-00071240/document

For å endre 'abc' til 'axbc' sender vi
insert{'a' < "x" < 'b'}
isteden for å sende 
insert{1, 'x'} 

** Hva med deletes?
Vi fjerner ikke.. bare markerer som deleted.

** Hvilke strukturer støtter woot?
Alle linjære datastrukturer, feks lister eller et tre med rekkefølge

** Konsistensmodell
*** Precondition preservation
Operasjoner blir applisert dersom de oppfyller preconditions
Erstatter Causality fra OT
*** Convergence
Alle klienter som har fått samme operasjoner 
applisert har samme state med et identiskt dokument
*** Intention preservation
Effekten av å applisere enhver operasjon er den samme 
på alle andre klienter som den er på kildeklienten

 




